Sun Apr 12 17:20:09 2020 : Traceback (most recent call last):
  File "f:/AutomateBoringStuff/Debugging/debug_ex_2.py", line 10, in <module>
    raise Exception("This is error message")
Exception: This is error message
Sun Apr 12 17:21:08 2020 : Traceback (most recent call last):
  File "f:/AutomateBoringStuff/Debugging/debug_ex_2.py", line 9, in <module>
    raise Exception("This is error message")
Exception: This is error message
